### PR TITLE
make throwing SBML load errors configurable

### PR DESCRIPTION
**Pull request by exaexa**

### CODE REVIEW

**Review by giordano — APPROVED** [review]
Nice!   Should be tested?

**Comment by anandijain** [comment]
is there one where i can just not see anything or pass an IO to redirect it?
when I run on all the biomodels, im going in expecting a bunch of warnings, but I don't need to see any of them

**Comment by anandijain** [comment]
is there one where i can just not see anything or pass an IO to redirect it?
when I run on all the biomodels, im going in expecting a bunch of warnings, but I don't need to see any of them

**Comment by exaexa** [comment]
> Nice! Should be tested?

Good question. I'd need to add a small broken model to test this properly, will add an issue and do it sometimes in the future.

**Comment by anandijain** [comment]
we should add that to the docs, i got the impression the only options were warn or fatal lol

**Comment by exaexa** [comment]
> we should add that to the docs, i got the impression the only options were warn or fatal lol

but it's in the docstrings?

**Comment by anandijain** [comment]
mirek! i cant read! didn't you know

**Pull request merged**
