### PR TITLE
Delete Manifest.toml

### PR DESCRIPTION
**Pull request by anandijain**
Manifest.toml is in the .gitignore, but it is in the repo?

### CODE REVIEW

**Comment by anandijain** [comment]
I'm not sure if this is sufficient (ie equivalent to `git rm --cached`)

**Comment by laurentheirendt** [comment]
nice catch - thanks 👍🏼

**Comment by exaexa** [comment]
just checking-- was this a remainder from the time we needed the CI to quickly take the newer version of SBML_jll?

**Comment by laurentheirendt** [comment]
Yes ... 👍🏼

**Pull request merged**
