### PR TITLE
Fix problems for reactions that don't have kinetic laws associated

### PR DESCRIPTION
**Pull request by exaexa**
Refs #16 

PS. it would be nice to bump version after this.

### CODE REVIEW

**Comment by laurentheirendt** [comment]
Is there any test for this?

**Comment by exaexa** [comment]
Travis is taking the old SBML_jll version again. Was there some trick to speed it up last time?

**Comment by exaexa** [comment]
Both SBML_jll and extra tests are fixed now.

**Review by laurentheirendt — APPROVED** [review]

**Comment by laurentheirendt** [comment]
maybe we should bump the version - can you do? thx

**Pull request merged**
