### PR TITLE
do not store kinetic law parameters as global parameters

### PR DESCRIPTION
**Pull request by exaexa**
(this was probably introduced by mistake)

### CODE REVIEW

**Comment by giordano** [comment]
Any meaningful test we can add?

**Comment by paulflang** [comment]
AFAIK the parameters stored in kinetic laws are local to that kinetic law.

**Comment by paulflang** [comment]
Anyway, looks good to me. But please up SBMLTk to get the downstream test working and make sure I haven't missed anything.

**Comment by exaexa** [comment]
(Scheduled after WriteSBML is merged)

**Pull request merged**
