### PR TITLE
Fix non-mandatory event IDs

### LINKED ISSUE #254: readSBML fails on SBML semantic test case 00928
## Minimal code example to reproduce the problem

```julia
using SBML
using Downloads
path = Downloads.download("https://raw.githubusercontent.com/sbmlteam/sbml-test-suite/release/cases/semantic/00928/00928-sbml-l3v2.xml", joinpath(@__DIR__, "model.xml"))
readSBML(path)

path = Downloads.download("https://raw.githubusercontent.com/sbmlteam/sbml-test-suite/release/cases/semantic/00929/00929-sbml-l3v2.xml", joinpath(@__DIR__, "model.xml"))
readSBML(path)
```

## Expected behavior

An SBML.model should be returned.

## Actual behavior

I received the following error message:

```julia
ERROR: ArgumentError: cannot convert NULL to string
Stacktrace:
 [1] unsafe_string
   @ ./strings/string.jl:84 [inlined]
 [2] unsafe_string
   @ ./c.jl:193 [inlined]
 [3] get_model(mdl::Ptr{Nothing})
   @ SBML ~/.julia/packages/SBML/wqJog/src/readsbml.jl:666
 [4] _readSBML(symbol::Symbol, fn::String, sbml_conversion::SBML.var"#69#71", report_severities::Vector{String}, throw_severities::Vector{String})
   @ SBML ~/.julia/packages/SBML/wqJog/src/readsbml.jl:191
 [5] readSBML(fn::String, sbml_conversion::Function; report_severities::Vector{String}, throw_severities::Vector{String})
   @ SBML ~/.julia/packages/SBML/wqJog/src/readsbml.jl:229
 [6] readSBML(fn::String, sbml_conversion::Function)
   @ SBML ~/.julia/packages/SBML/wqJog/src/readsbml.jl:222
 [7] readSBML(fn::String)
   @ SBML ~/.julia/packages/SBML/wqJog/src/readsbml.jl:222
 [8] top-level scope
   @ ~/.julia/dev/PEtab/test/Boehm.jl:221
```

## Optional: Suggestions for fixing

My PEtab importer [PEtab.jl](https://github.com/sebapersson/PEtab.jl) has a SBML importer for ODE models. I am currently working through the [SBML test suite](https://github.com/sbmlteam/sbml-test-suite/tree/release/cases/semantic), and for cases with EventT0Firing (case 928 and 929) I receive the above error message. 

Besides this SBML.jl has worked great, and thanks for creating a SBML importer in Julia! :)

### PR DESCRIPTION
**Pull request by exaexa**
Mainly fixes #254 using approach #1. As a result, some new SBML usecases can be loaded.

I packed in the UL logo update (the original relied on line width setting and rendering, which is typically broken. 

Also bumping to 1.5.0 (the new loadable models are a feature, also see discussion in the commits).

### CODE REVIEW

**Comment by exaexa** [comment]
cc @sebapersson -- I added one of the models you reported as a test so this _should_ technically work, but it would ne great if you could check if your usecase is solved. Thanks!

**Review by paulflang — APPROVED** [review]
Thanks. Looks good to me!

**Review by stelmo — APPROVED** [review]

**Comment by sebapersson** [comment]
> cc @sebapersson -- I added one of the models you reported as a test so this _should_ technically work, but it would ne great if you could check if your usecase is solved. Thanks!

Thanks, it now works for my usercase.

**Comment by exaexa** [comment]
Perfect, thanks all for confirms!

**Pull request merged**
