### PR TITLE
Mention UCL contribution to the package

### PR DESCRIPTION
**Pull request by giordano**

### CODE REVIEW

**Comment by exaexa** [comment]
Looks okay, can you pls add the unbreakable spaces before the logo to add the (required) padding?
image

(it looks like the spaces between files are 3 normal spaces, but they aren't. I didn't find a better way to smuggle this to markdown tho :(  )

**Comment by exaexa** [comment]
@laurentheirendt I think there's no conflict with permedcoe&other acks here, but requesting review just to be triple sure. :D

**Review by laurentheirendt — APPROVED** [review]
I am ok with this, of course, but I let @weiguUL have a look as well 👍🏼

**Comment by weiguUL** [comment]
> I am ok with this, of course, but I let @weiguUL have a look as well 👍🏼

I am fine. Could we use the full logo of PerMedCoE (to make all logos similar in size)? @exaexa

**Pull request merged**
