### PR TITLE
Add mapping of `rateOf` for Symbolics

### PR DESCRIPTION
**Pull request by giordano**
Ref #139.  @paulflang would this work for you?

### CODE REVIEW

**Comment by exaexa** [comment]
Looks great to me. Is there a SBML testcase that would trigger the code to get coverage?

**Comment by paulflang** [comment]
I think we would have to automatically connect to the other reactions. Unless ModelingToolkit is very smart in its simplifications and does that for us. But it is definitely a step in the right direction.

**Comment by giordano** [comment]
>  we would have to automatically connect to the other reactions.

Do we already do something like that elsewhere in `SBML.jl`?

**Comment by paulflang** [comment]
`extensive_kinetic_math`
 does sth somewhat similar: looking up the species in a `kineticLaw` and depending on whether they have `hOSU` correcting for volume: https://github.com/LCSB-BioCore/SBML.jl/blob/1aa07d4fb21a361ae36cbb6963ad30640309f4eb/src/utils.jl#L193

**Comment by exaexa** [comment]
Hey guys esp @paulflang is this okay to merge ie doesn't it kill any usecases for you? I'd smash it into 0.8.1 (reqd by anand in the other PR)

**Review by exaexa — APPROVED** [review]
after quick checking it doesn't seem to me this would break any package in the environs; I guess we're good to go

**Comment by paulflang** [comment]
Don't think it kills anything, so should be fine.

**Pull request merged**
