### PR TITLE
fix parsing of relational operators

### LINKED ISSUE #124: Extracting math with <geq/> returns a zero character
## Minimal code example to reproduce the problem

load SBML test 00191-l3v2

## Problematic behavior

kinetic math of model reaction `reaction2` is:
```
SBML.MathApply("piecewise", SBML.Math[SBML.MathIdent("p1"), SBML.MathApply("\0", SBML.Math[SBML.MathIdent("S2"), SBML.MathVal{Int32}(4)]), SBML.MathIdent("p2")])
```

ie contains a function with name `"\0"`

Originally there should have been an equivalent of `<geq/>` but no idea where that disappeared. What's the correct way to get the "content" of relational math function from SBML? Ideally without copying the C++ enums (in particular this one: http://sbml.org/Software/libSBML/docs/c-api/_a_s_t_node_type_8h.html#a67bf7933ff8461eb28819ed744bf3203 )

## Notes

This is the second issue from #112 that @paulflang reported.

### PR DESCRIPTION
**Pull request by exaexa**
fixes #124

### CODE REVIEW

**Comment by exaexa** [comment]
@paulflang this fixed the dynamic biomodels for me (see issue in SBMLToolkit)

**Review by giordano — APPROVED** [review]
Change looks good, maybe can add a test? :slightly_smiling_face:

**Comment by exaexa** [comment]
a test you say...

**Comment by exaexa** [comment]
....mind if I repurpose the units.xml? :D

**Comment by giordano** [comment]
Not at all :smile:   Can also rename it :slightly_smiling_face:

**Comment by exaexa** [comment]
ah I found one in SBML, looks good.

**Pull request merged**
